/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.14.v202310241606.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v2/de/bmw/infotainment/telematic/simprofileselector/SimProfileSelectorSomeIPDeployment.hpp>

namespace v2 {
namespace de {
namespace bmw {
namespace infotainment {
namespace telematic {
namespace simprofileselector {
namespace SimProfileSelector_ {

// Type-specific deployments

// Attribute-specific deployments
CommonAPI::SomeIP::StringDeployment csimNetworkStatusDeployment(510, 4, CommonAPI::SomeIP::StringEncoding::UTF8);

// Argument-specific deployment

// Broadcast-specific deployments

} // namespace SimProfileSelector_
} // namespace simprofileselector
} // namespace telematic
} // namespace infotainment
} // namespace bmw
} // namespace de
} // namespace v2
