/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.14.v202310241606.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */

#ifndef DE_BMW_INFOTAINMENT_TELEMATIC_SIMPROFILESELECTORTYPES_SIM_PROFILE_SELECTOR_TYPES_SOMEIP_DEPLOYMENT_HPP_
#define DE_BMW_INFOTAINMENT_TELEMATIC_SIMPROFILESELECTORTYPES_SIM_PROFILE_SELECTOR_TYPES_SOMEIP_DEPLOYMENT_HPP_


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif
#include <CommonAPI/SomeIP/Deployment.hpp>
#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace de {
namespace bmw {
namespace infotainment {
namespace telematic {
namespace simprofileselectortypes {
namespace SimProfileSelectorTypes_ {

// typecollection-specific deployment types
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> ChangePinResultDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> ConfigureDataConnectionResultDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> ConfigureProfileRoamingResultDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> CSimProfileStatusDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> DisablePinResultDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> EnablePinResultDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> InstallationErrorsDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> RequestDeleteAllResultDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> RequestDeleteSimProfileResultDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> RequestDisableSimProfileResultDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> RequestEnableSimProfileResultDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> SendActivationCodeResultDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> UnblockPinResultDeployment_t;

typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> VerifyPinResultDeployment_t;

typedef CommonAPI::SomeIP::StringDeployment ActivationCodeDeployment_t;

typedef CommonAPI::SomeIP::StringDeployment ConfirmationCodeDeployment_t;

typedef CommonAPI::EmptyDeployment CSimProfileLockStatusDeployment_t;

typedef CommonAPI::SomeIP::StringDeployment EidDeployment_t;

typedef CommonAPI::SomeIP::StringDeployment IccidDeployment_t;

typedef CommonAPI::SomeIP::StringDeployment ImeiDeployment_t;

typedef CommonAPI::SomeIP::StringDeployment MetaInfoDeployment_t;

typedef CommonAPI::SomeIP::StringDeployment PinDeployment_t;

typedef CommonAPI::SomeIP::IntegerDeployment<uint8_t> PinRetriesDeployment_t;

typedef CommonAPI::SomeIP::StringDeployment PukDeployment_t;

typedef CommonAPI::SomeIP::IntegerDeployment<uint8_t> PukRetriesDeployment_t;

typedef CommonAPI::SomeIP::IntegerDeployment<int64_t> TimestampDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    ::de::bmw::infotainment::telematic::simprofileselectortypes::SimProfileSelectorTypes_::SendActivationCodeResultDeployment_t,
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>
> ActivationCodeResultDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    ::de::bmw::infotainment::telematic::simprofileselectortypes::SimProfileSelectorTypes_::VerifyPinResultDeployment_t,
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>
> CheckPinResultDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    ::de::bmw::infotainment::telematic::simprofileselectortypes::SimProfileSelectorTypes_::UnblockPinResultDeployment_t,
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>
> CheckPukResultDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::StringDeployment,
    ::de::bmw::infotainment::telematic::simprofileselectortypes::SimProfileSelectorTypes_::CSimProfileStatusDeployment_t,
    CommonAPI::EmptyDeployment,
    CommonAPI::SomeIP::StringDeployment,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>,
    CommonAPI::SomeIP::IntegerDeployment<int64_t>
> CSimProfileDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    ::de::bmw::infotainment::telematic::simprofileselectortypes::SimProfileSelectorTypes_::ConfigureDataConnectionResultDeployment_t,
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>
> DataConnectionConfigResultDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    ::de::bmw::infotainment::telematic::simprofileselectortypes::SimProfileSelectorTypes_::RequestDeleteAllResultDeployment_t,
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>
> DeleteAllResultDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    ::de::bmw::infotainment::telematic::simprofileselectortypes::SimProfileSelectorTypes_::RequestDeleteSimProfileResultDeployment_t,
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>
> DeleteResultDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    ::de::bmw::infotainment::telematic::simprofileselectortypes::SimProfileSelectorTypes_::RequestDisableSimProfileResultDeployment_t,
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>
> DisableResultDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    ::de::bmw::infotainment::telematic::simprofileselectortypes::SimProfileSelectorTypes_::RequestEnableSimProfileResultDeployment_t,
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>
> EnableResultDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    ::de::bmw::infotainment::telematic::simprofileselectortypes::SimProfileSelectorTypes_::InstallationErrorsDeployment_t,
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>,
    CommonAPI::SomeIP::StringDeployment
> InstallationResultDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    ::de::bmw::infotainment::telematic::simprofileselectortypes::SimProfileSelectorTypes_::ChangePinResultDeployment_t,
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>
> ModifyPinResultDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    ::de::bmw::infotainment::telematic::simprofileselectortypes::SimProfileSelectorTypes_::DisablePinResultDeployment_t,
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>
> RemovePinResultDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    ::de::bmw::infotainment::telematic::simprofileselectortypes::SimProfileSelectorTypes_::ConfigureProfileRoamingResultDeployment_t,
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>
> RoamingConfigResultDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    ::de::bmw::infotainment::telematic::simprofileselectortypes::SimProfileSelectorTypes_::EnablePinResultDeployment_t,
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>
> SetPinResultDeployment_t;


// typecollection-specific deployments
COMMONAPI_EXPORT extern CommonAPI::SomeIP::StringDeployment InstallationResult_functionExecutionStatusDeployment;
COMMONAPI_EXPORT extern ::de::bmw::infotainment::telematic::simprofileselectortypes::SimProfileSelectorTypes_::InstallationResultDeployment_t InstallationResultDeployment;

} // namespace SimProfileSelectorTypes_
} // namespace simprofileselectortypes
} // namespace telematic
} // namespace infotainment
} // namespace bmw
} // namespace de

#endif // DE_BMW_INFOTAINMENT_TELEMATIC_SIMPROFILESELECTORTYPES_SIM_PROFILE_SELECTOR_TYPES_SOMEIP_DEPLOYMENT_HPP_
