
/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.14.v202310241606.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <de/bmw/infotainment/telematic/simprofileselectortypes/SimProfileSelectorTypesSomeIPDeployment.hpp>

namespace de {
namespace bmw {
namespace infotainment {
namespace telematic {
namespace simprofileselectortypes {
namespace SimProfileSelectorTypes_ {

// typecollection-specific deployments
CommonAPI::SomeIP::StringDeployment InstallationResult_functionExecutionStatusDeployment(200, 4, CommonAPI::SomeIP::StringEncoding::UTF8);
::de::bmw::infotainment::telematic::simprofileselectortypes::SimProfileSelectorTypes_::InstallationResultDeployment_t InstallationResultDeployment(0, static_cast< ::de::bmw::infotainment::telematic::simprofileselectortypes::SimProfileSelectorTypes_::InstallationErrorsDeployment_t* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint16_t>* >(nullptr), &::de::bmw::infotainment::telematic::simprofileselectortypes::SimProfileSelectorTypes_::InstallationResult_functionExecutionStatusDeployment);

} // namespace SimProfileSelectorTypes_
} // namespace simprofileselectortypes
} // namespace telematic
} // namespace infotainment
} // namespace bmw
} // namespace de
